apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-deployment
  labels:
    app: insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
      - name: insurance-container
        image: madhu112234/insurance:1.0
        ports:
        - containerPort: 8081
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: insurance-service
spec:
  selector:
    app: insurance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: NodePort
